SixTrack/crlibm/Makefile.template, SixTrack/make_six, SixTrack/makefile
This patch changes make_six, the crlibm makefile, and the sixtrack makefile to always use SSE math with gfortran. This makes the newer gfortran versions pass all the SixTrack checks, while having no effect on the results from earlier versions of gfortran.
This should probably be discussed with Eric etc.
I could not get the exact same results using the sixtrack makefile, but I suspect that this is rather due to the OPTIONS which I passed to it.
This patch fixes issue #12 .
=> Use SSE for floating point math, no more x87.

SixTrack/sixtrack.s
- Cleaned up nzfz
- Error checking: When preparing random numbers, confirm that nzfz is actually big enough.
- Input checking: Single element names (bez entries) should be unique. At least for some FCC lattices this was not the case; this will now be detected and produce an error.
- Add the unit [1] in the header for the DUMP dE/E output
- Comments and code formatting...
=> For version 4.5.32:

SixTrack/sixtrack.s
When writing in sigmasettings.out/twisslike.out, tctps where not correctly identified, since string matching was truncating the bez() to 4 chars instead of 5.
Moreover, few extremely long lines (full of empty spaces) removed.
=> bug fix to rbruce-morecollimator.

SixTrack/ast_mask/sixda.ast
Fix from Eric which makes the Differential Algebra version compile without complaining about linker error to COMNUL and various DYNK routines.
=> Add DYNK to SixDA

SixTrack/sixtrack.s
Including writing out the twiss functions for +23 (not only -23) when in collimation version.
=> In LINOPT: Treat crab cavity dipoles the same way as other RF multipoles.

Doc/physics_manual/sixphys.tex
The octupole py-kick was wrong.
=> Correct typo in physics manual spotted by Adrian Oeftiger

SixTrack/make_six
Delete if statement hardcoding specific -L path for unrecognized gfortran versions (not 4.4 or 4.5) - the linker should figure it out itself. This was making problems for Frank Schmidt on Fedora23.
I tested the patch on CC7.2.1511 (gfortran 4.8.5), SLC6.7 (lxplus, gfortran 4.4.7), Fedora23 (5.3.1), Ubuntu 15.10 (gfortran 5.2.1) and it works without any problems. My workstation is quickly turning into a virtualbox zoo...
It may be a good idea to clean up the other compilers as well, but this should fix the issue for 99% of the developers.
=> Simplify make_six

SixTrack/bdex_echo.py, SixTrack/make_six, SixTrack/sixtrack.s
As described in issue #59 , this patch allows exchanging the particle distribution at some element.
TODO:
- Binary format in order to avoid roundoff errors, or at least CRLIBM (if not already there?)
- Documentation
- More than just thin6d tracking (this could also be implemented in a later patch)?
- Testing...
Related development: DYNK-PIPEFUN, pull request #66 .
=> BDEX: Beam Distribution EXchange

SixTest/read90/read90.f90
This should allow writing the read90 output to a file given by the --ofile option.
Could somebody please check I've not done something insane here :)
=> Add the option to output to a specified file in read90

SixTrack/make_six, SixTrack/plato_seq.s, SixTrack/sixtrack.s
It seems DFLOAT is a language extension that converts an integer to a double.
This does not seem to be supported by nagfor any more.
The standard way seems to be to call DBLE instead.
This just replaces calls to DFLOAT with calls to DBLE.
=> Replace calls to DFLOAT with DBLE.

SixTest/bin/checkf10.f, SixTest/bin/checkf1014.f, SixTest/bin/checkf110.f, SixTest/bin/compf10.f, SixTest/bin/verify10.f
As the title says....
Now it prints out the same output each time (when you run without an input file).
=> Fix test check tools to not print out random memory contents.

SixTrack/buildLibraries.sh
Otherwise build on e.g. MINGW64 breaks if you previously built MINGW32.
=> Have it always rebuild boinc_api_fortran.o for new arch

SixTest/bin/checkf10.f, SixTest/bin/checkf1014.f, SixTest/bin/checkf110.f, SixTest/bin/compf10.f, SixTest/bin/verify10.f
Nagfor was giving errors
```
checkf10.f, line 31: Unit 20 is not connected on OPEN with STATUS='OLD' and no FILE= specifier
Program terminated by fatal I/O error
```
=> Fix runtime warning in test programs with Nagfor.

SixTrack/sixtrack.s
This file, written by the collimation version, contains basically a DUMP of all particles at every element at every turn.
It is huge. It makes things take twice as much time as needed (see https://indico.cern.ch/event/623918/contributions/2517815/attachments/1430968/2198642/2017-03-21_SixTrack-COLL-improvements.pdf ). It is not used by anyone. It needs to go.
This patch therefore comments it out.
=> Comment out FirstImpacts_AcceleratorFrame.dat

CMakeLists.txt
This fixes some issues I had with different g++ versions on aarch64.
I also checked it doesn't cause issues on default lxplus.
=> Force static linking of libstdc++ if a static build is requested.

SixTrack/libArchive_wrapper.c, SixTrack/lielib.s, SixTrack/sixtrack.s
Debugging failed BOINC runs tends to be quite difficult; this patch should make it easier:
* It puts the error messages in stderr, which is returned by the client
* When something fails, it sets another return code than 0; zero is reserved for successful runs ONLY.
* All failure exits in SixTrack now call prror, nowhere except the bottom of program `maincr` and `mainda` calls STOP/ABEND/etc. directly.
This part is therefore in principle done. I would however want to look for a problem in SixTestWrapper - for quick / failed runs, it seems to always restart the process over and over; it should probably also look at the exit code of SixTrack.
=> Error output

SixTrack/sixtrack.s
SixTrack was crashing on BOINC when trying to open Sixin.zip because it did not know how to deal with a "linked" file. This fixes this, and also calls boincrf before every file opening statement (except in parts of the code that anyway doesn't support BOINC).
=> Call BOINCRF

SixTrack/sixtrack.s
It seems that 'stop INTEGER' where INTEGER is evaluated at run-time is only valid in Fortran 2008.
Replaced by something which works in pre-2008 as well, so that we can build it with gfortran older than 6.0.
=> Change STOP statements for pre-Fortran2008 compatibility

SixTrack/sixtrack.s
Previously, the DUMP, dynksets, and (theoretically fort.6) files were repositioned in a way that was unsafe. This could lead to incorrect results in the output, with doubled- or missing lines, or crashes.
This patch fixes #281 .
=> Safe and correct repositioning of files

Doc/user_manual/makefile, Doc/user_manual/six.tex
Clear up some confusion in the user manual about the variable `ird`, and bump it's version to 4.6.30.
=> Fix manual for variable `ird`

SixTrack/sixtrack.s
Beginning a parenthesis twice in a +if block broke syntax highlighting. These repeated code lines were also inconsistent in the source. Parentheses are now closed properly in all four blocks.
=> Fixed some code formatting that broke syntax highlighting

SixTrack/sixtrack.s
No tests needed to be changed - seems that gfortran (which I was using for the testing) was doing the right thing when reading!
Note: Should also be tested with ifort and nagfor (ideally before and after).
Tests using fort.13:
```
SixTest $ find . -name "fort.13"
./javier_bignpart/fort.13
./rfMultipoles_3rdOrder/fort.13
./rfMultipoles_2ndOrder/fort.13
./scatter_bbelastic/fort.13
./beam-HO_4D-newstyle-loadParticles/fort.13
./thick6ddynk/fort.13
./beam-HO_6D-simple-newstyle-coupling/fort.13
./rfMultipoles_4thOrder/fort.13
```
=> Round properly when reading fort.13

SixTrack/scatter.s90
Added some dummy values in a currently not used function to stop ifort from complaining
=> Scatter: Quiets a compiler warning

CMakeLists.txt
Some systems, e.g. ubuntu. still have a compiler that does not enable c++11 by default.
The test tool needs c++11, therefore the build explodes.
This change fixes this...
=> Fix building testing on some systems

SixTrack/collimation.s90, SixTrack/scatter.s90, SixTrack/sixtrack.s90
Here are the proposed changes to mark the particles as "dirty" for collimation, which should result in them being written to tracks2.dat etc.
I added one more parameter to scatter_thin (the structure element ID); it may be a good idea to also write this and/or the element s-position (`dcum` array AFAIK) to the SCATTER output file.
=> Mark SCATTERed particles as dirty for collimation

SixTrack/aperture.s90, SixTrack/collimation.s90, SixTrack/sixtrack.s90
- Check for the full element names when searching for collimators instead of (1:11) - this was finding aperture markers instead.
- @amereghe  - I changed the call in daten to call aperture_initroffpos() so you may want to merge this into your branch.
=> Collimation and aperture updates

CMakeLists.txt, SixTrack/ast_mask/mod_alloc.ast, SixTrack/dump.s90, SixTrack/mod_alloc.f90, SixTrack/strings.f90
Added three new routines to strings:
* aString%upper() : Replaces [a-z] with [A-Z]
* aString%lower() : Replaces [A-Z] with [a-z]
* aString%strip() : Removes leading and trailing spaces
* aString%strip(zero=.true.) : Also cuts at first char(0)
mod_alloc
* Fixed the indexing of alloc and resize in mod_alloc for all with an optional first index not equal to 1
* Added 1D string array support
=> Strings module and mod_alloc index fix

SixTrack/cmake_six
=> Revert "Fixed cmake_six after file rename"

SixTrack/cmake_six, SixTrack/dynk.s90
Changes that I think should fix the remaining bugs in ENVARSV, after carefully reading the energy update code in `thck6dua` and `thin6dua`.
Note: In the old code, the algorithm was as follows:
* Store original e0 and e0f
* Update e0 and e0f
* For each particle:
* if (sigma < 0): sigma = (beta0 / beta0_old) * sigma
* Energy kick from the cavity && update of variables
* if (sigma > 0): sigma = (beta0 / beta0_old) * sigma
* In thick only: Call `synuthck`
I'm a bit confused about why it does the sigma update the way it is done...
Things still to be done:
* Delete the now superfluous and commented-out code from `sixtrack.s`
* Delete variables `phas0`, `e0o`, `e0fo`, `xv1j`, `xv2j`
* Make variables `nde(1)` and `nde(2)` -- the number of turns at flat bottom and for energy ramping -- invalid in …
=> Fix DYNK GLOBALVARS energy update to work with THICK and SIGMAV

SixTrack/ast_mask/bdex.ast, SixTrack/ast_mask/beamgas.ast, SixTrack/ast_mask/collimation.ast, SixTrack/ast_mask/fluka.ast, SixTrack/ast_mask/hions.ast, SixTrack/ast_mask/parpro_scale.ast, SixTrack/ast_mask/postprocessing.ast, SixTrack/ast_mask/sixve.ast, SixTrack/ast_mask/sixvefox.ast, SixTrack/ast_mask/track.ast, SixTrack/dynk.s90, SixTrack/postprocessing.s90, SixTrack/sixtrack.s90
This removes the vvector flag. For standard SixTrack vvector is always on.
For DA version, the previously `+if .not.vvector` sections have now been changed to `#ifdef DA`
=> End of vvector

SixTrack/dump.s90, SixTrack/sixtrack.s90
This PR fixes a bug related to replacing fort.92 when restarting from checkpoint, and wrong initialisation of CR arrays in DUMP.
=> CR bug fixes

SixTrack/hdf5_output.f90, SixTrack/sixtrack.s90, SixTrack/sixtrack_input.f90, SixTrack/string_tools.f90
Removed support for single quoted strings in string_tools split routines. There was no checking that they single and double quoted regions overlapped, and there really isn't a need to support both formats. It is now only double quoted.
Also added some more simulation information to HDF5 output.
In addition, string_tools now have routines to cast logicals.
=> Some minor changes and updates

source/end_sixtrack.f90, source/sixtrack.f90
This is a fix that caused DATEN to interpret the PRIN command in the LIMI block as the PRINTOUT flag that sits at the top of fort.3.
The conflict arises because Sixtrack pre-5.0 did not enforce a NEXT flag after the PRINTOUT statement. Since the new input parser has a global loop instead of a loop per block, this caused the PRIN command to be parsed as a PRINTOUT flag and the settings therefore ignored.
Ideally we should require the PRINTOUT block to be closed, but this fix should be able to handle the un closed case better than the previous code did.
=> Fix for PRINT block conflict with LIMI block

source/file_units.f90, test/fileunits_DYNK_DUMP/file_units.dat.canonical
This PR fixes issue #591 by having the file_units module bypass the funit_requestUnit call when assigning a file unit to its own log file.
=> Fileunits fix

source/aperture.f90, source/track_thick.f90, source/track_thin.f90
restoring `call aperture_saveLastCoordinates(i,ix,-1)` but in the proper place (i.e. after any element where the online aperture checking has killed particles), and removed `call aperture_saveLastCoordinates(i,ix,0)` after any element. This last call was also fooling the backtracking algorithm, as the particle angles after the lens were saved and used, instead of the angles before the lens. hence the aperture checking was wrongly computing the transverse position of the lost particles (and also the longitudinal position, possibly not by a large amount).
At the same time, fixed bug at printing level - in previous dump, in case back-tracking was requested but not possible, the s-location of the last aperture marker was dumped instead of the last particle coordinates saving.
Pull request …
=> Online ape check fixes

CMakeLists.txt
This does some further cleanup of CMakeLists from #593 
The PR did not include the include files as dependencies, however, that seems to be a difficult thing to achieve as CMake does not resolve the dependencies itself, so it needs to be added in another way.
As it stands, if include files are changed, a full rebuild is required.
Still adding this PR as some redundant stuff has been cleaned out.
=> More cleanup in CMake

.circleci/config.yml, .gitignore, doc/user_manual/makefile, test/CMakeLists.txt, test/CheckBuildManual.sh
This PR adds a test for the user manual build.
I updated the makefile as well.
The test runs in the user manual folder directly, but I don't think that is a problem.
I assume the circleci test will fail as latex is not installed there.
=> User manual build test

CMakeLists.txt, buildLibraries.sh
While adding support for building SixDA with LIBARCHIVE, we forgot to disable if both BOINC and LIBARCHIVE is built. This fixes that.
Also adds a section in buildLibraries.sh that updates two source files in BOINC before build when run on MinGW.
=> Build bugfixes

source/dynk.f90
Incrementing of dynk_niData was missing in FIR/IIR parsing. Failed bounds check with debug.
=> Bugfix for DYNK FIR/IIR

source/dynk.f90
Fixes IIR the right way by completely removing the broken and unused variable. This superseedes #650 and should be merged once #651 (which reverts #640 ) has been merged.
=> Fix IIR the right way

source/beamgas.f90
BEAMGAS flag now builds again. Was just missing a `use mod_hions`.
Also, in the same PR, the hard coded file units have been replaced by units assigned by the `file_units` module.
=> Beamgas build fix

source/ranecu.f90
Minor update to the random number generator.
The code has been re-indented and cleaned up a bit (commit 1), and a new routine `recuinit` for initialising the random generator with either one or two seeds has been added (commit 2). This init routine should replace calls to `recuin` when setting the seeds provided in `fort.3` during input parsing. `recuinit` ensures the seeds are within valid range, and will generate a reasonable seed2 if only one seed is provided.
=> Ranecu Updates

doc/user_manual/chGeneralInput.tex, source/common_modules.f90, source/main_cr.f90, source/sixtrack.f90, source/sixtrack_input.f90, source/string_tools.f90, source/track_thin.f90
This PR adds a flag to the `SETTINGS` block that controls writing the particle summary at the end of the simulation. The amount of output is also controlled by the `QUIET` flag as before.
The new flag is `PARTICLESUMMARY` and when present is taken as `.true.`. An explicit parameter can be added, as the default behaviour otherwise depends on the number of particles tracked. If it is 64 or less, it is on by default, and otherwise it is off.
A modification to the `chr_cast` routine: it now also accepts `ON` and `OFF` as logical values (should work wherever the casting routine is used for parsing.) In relation to that, I also added two functions to the `string_tools` module for converting a string to upper or lower case. `chr_toUpper` and `chr_toLower`.
This PR also stops `track_thin` from …
=> Less fort.6 output

source/sixtrack.f90, source/track_thick.f90, source/track_thin.f90
These allocations should not be necessary as `npart` is -1 at this point, and the arrays are anyway used locally in tracking.
Also cleaned trailing spaces when I had the files open.
=> Removed unnecessary array allocations in daten.

CMakeLists.txt
Doesn't seem to have any performance effect, but this at least allows LTO to be built for ifort.
=> Added missing flag for ifort LTO.

source/main_cr.f90, source/main_da.f90, source/read_input.f90
This PR moves the parsing of fort.13 into a separate module for "legacy" input files. It also uses the automatic casting routines from string_tools.
This is a branch off of #684, so should be reviewed and merged after that.
=> Moving parsing of fort.13 out of maincr

devtools/plotPerformance/runTests.py
Quite dirty script, but at least one has a feeling of the CPU time taken by tests.
The script runs the tests N times and stores the `STDOUT` of `ctest` in specific folders labelled by the commit hash (must be provided by user). Afterwards, the script looks for all `STDOUT` files saved, including those of previous commits, and plots the evolution of all the requested plots, one by one.
Total CPU time is also plot
=> python script to plot cpu times of tests

source/main_da.f90, source/mod_time.f90, source/zipf.f90
Fixed a bug in mod_time that caused division by zero when running DA version where nTurnPart = 0.
This only affected Debug builds.
Also fixed the bug in ZIPF with BOINC. I already fixed it, but it looks like I forgot to include it in the previous PR.
=> Bug fixes before50003

CMakeLists.txt, source/mod_fluka.f90
Two minor bugs fixed.
* HASHLIB flag depended on roundctl, which broke single and quad build
* FLUKA module was still expecting fluka_lostpart to exist. The routine has been renamed.
=> Bugs 2018 12 06

CMakeLists.txt, source/main_cr.f90, source/mod_units.f90, source/track_thin.f90
A few tweaks here and there, in CMake and main_cr mainly, while trying to sort out the segfault issues on debian/ubuntu with gcc/gfortran.
This PR also bumps the BOINC API to latest client version, 7.14.2.
Needs testing on Windows, both for changes here, and those from PRs #743 and #732.
=> CMake updates BOINC etc

CHANGELOG.md, lib/buildBoinc.sh, source/version.f90
Version bump and latest Boinc version.
Using latest Boinc fixes most build issues on Windows, but the issue with `windows.h` remains. This PR runs of a branch that fixes this in our Boinc fork.
=> Release 5.1.1

source/aperture.f90, source/main_cr.f90, source/main_da.f90, source/mod_units.f90, source/sixtrack.f90
Tests with BOINC build failed due to extraction of Sixin.zip not triggering. Issue resolved.
In the process, I also clarified an error message in daten, moved the opening of fort.2 and fort.3 there, and came across an issue with restarting aperture_losses file when running CR.
Note: file unit variables should never be initialised as 0, because 0 is the error unit. They should always be initialised as -1, which will cause a critical error if uninitialised when writing occurs. I.e. easier to trap.
=> Boinc Sixin.zip fix

source/aperture.f90, source/sixtrack.f90
This PR fixes issues with parsing aperture file from `LOAD` statement, so that:
* any keyword in the `LIMI` block is no longer ignored, as it was the case so far;
* the code is cleaner.
=> Fixing parsing file of aperture

source/common_modules.f90, source/constants.f90, source/lielib.f90, source/sixda.f90
Moved the four variables based on pi to numerical_constants and changed them to parameters.
Not sure why this wasn't done when the many definitions of pi were cleaned up.
=> Pi to numerical_constants

source/cheby.f90, source/collimation.f90, test/collimation_k2_fcc_2017_h1_collision/hash.md5.canonical
Fixes:
* Kills a warning in cheby.f90 when building with ifort
* Fixes headers of some of the collimation files which were written with format *, and thus looked different between gfortran and ifort. This failed the `collimation_k2_fcc_2017_h1_collision` test.
=> Fixes for 5.2

test/CMakeLists.txt
There is no point running the collimation tests with CR on as they just exit with an error anyway. It generates false fails on the nightly builds.
We can turn them back on when collimation supports CR.
=> Disable collimation tests when building with CR

source/aperture.f90
Fixed bug in aperture with write format 'l' instead of 'l1'
=> Nagfor bug fixes for 5.2

doc/user_manual/chIntroduction.tex, source/string_tools.f90
The routine to cast strings to logicals was updated in another branch, but never merged.
All of this was in the SIMU block PR. Moved here now.
=> Minor fix in String Tools

source/common_modules.f90, source/main_cr.f90, source/mainarrays.f90, source/sixve.f90
Remove a few global arrays that were only used one place, and removed the allocate thickarrays routines from the common modules as the expand thickarrays routines do the same thing.
=> Minor cleanup

source/sixtrack.f90
A bit of code was skipped if the PRINT flag was off, causing a segfault due to negative index as it computes `kz(k) = abs(kz(k))` for `kz(k) == 12`.
=> Print flag bug

test/CMakeLists.txt
Moves the chebythin6d_ramp_DYNK and elensidealthin6d_ramp_DYNK tests to medium tests.
They are only over the threshold on circleci, but I'd like to move them anyway. They are run on nightly builds still.
=> Move a couple of fast tests to medium tests

source/constants.f90, source/dabnew.f90
Just another small change on my todo list.
I've defined all the constants that are pi-related (and two more) in terms of a correctly truncated binary representation. They are all based on the gfortran casting of the quad precision, and tuned to produce the exact same binary to the size of the mantissa for double and single precision. 
**Changes**
* The double precision one was corrected in the last bit for the `eulergamma` variable (which is the same as stated on wikipedia, but the variable isn't used anywhere in SixTrack currently anyway). 
* All of the single precision variables were corrected on the last bit. That is, setting the values with the full list of decimals tended to round the last bit up for single precision, while the corresponding double precision bit was lower. …
=> Hexadecimal version of pi and pi-related constants

source/constants.f90
Transfer from hex to real128 is not necessarily allowed, but the GNU compiler allows it and handles it as expected. Intel does not allow it at all, and NAG allows it by truncating to double precision first.
This PR alters the constants file to only use transfer from hex for gfortran, and use the old method for other compilers.
This is tested with gfortran 8.3 and 6.3. Both produce the same binary value for pi for quad precision.
=> Hex pi fix for ifort and nagfor

source/end_sixtrack.f90, source/sixtrack_input.f90, test/CMakeLists.txt
This PR fixes a few bugs caught by nightly build.
**Summary**
Most of the errors were related to the error tests failing due to inconsistent output used for diff in CR versions (non-critical). The correction of the `imc` variable check in `TRAC` parsing in PR #847 revealed an existing issue with an uninitialised dummy variable. Only critical if the `imc` variable was not set in the `TRAC` block, and the compiler was not gfortran.
**Fixes**
* Cannot build error tests when BOINC flag is on as there is no initial `fort.3` file. For this to work, the python wrapper needs to make the Sixin.zip files on the fly. It is not really necessary to build the error tests with BOINC, so they are now disabled.
* When running error tests with CR (non-BOINC build) the content of the `fort.91` file was not …
=> Bugfixes 2019-04-25

source/cheby.f90, source/elens.f90
This #PR allows to set R1=0.0 for both elenses and chebyshev maps, even though the fox implementation is still on-going (elens: https://github.com/SixTrack/SixTrack/pull/839, chebyshev maps: https://github.com/SixTrack/SixTrack/pull/849). At least, this PR will allow running full elens studies, even though the closed orbit does not take into account these elements...
=> removing constraint on R1=0.0 in chebyshev maps and elenses

test/error_init/errorTests.py, test/error_trac/errorTests.py
Running the error tests fails when compiling SixTrack as `./cmake_six BUILD_TESTING", since when running a symlinked python script it looks for modules in the folder the script is symlinked from, not in the working directory.
=> Make the error tests work when the supporting library is symlinked in

source/checkpoint_restart.f90, source/common_modules.f90, source/main_cr.f90, source/sixve.f90, source/track_thick.f90
Spotted more arrays that do not need to be arrays any more.
* For `ekv(j,l)` all `j` were set to `ek(l)` where `j` is particle id and `l` is single element id. `ekv(j,l)` replaced by `ek(l)`.
* `fokqv(j)` only contained `ekv(j,l)` times a sign that depended on horisontal or vertical magnet. Since `ekv` was repalced with `ek`, there is no longer a particle ID dependency, so it's a single variable with a sign per element.
* There is no need to checkpoint the arrays `dpd`, `dpsq`, `as`, and `al`. These are computed by the subroutine `synuthck`, and can just be recomputed from energy/momentum arrays after restart.
=> More thickarray cleanup

source/postprocessing.f90
Single and Quad build broke because one of the subroutines in postprocessing was getting some definitions from the use calls I cleaned up in floatprecision.
Single line fix.
=> Single/Quad Fix

source/common_modules.f90, source/include/alignva.f90, source/include/kickvho.f90, source/main_cr.f90, source/main_da.f90, source/postprocessing.f90, source/six_fox.f90, source/sixda.f90, source/sixtrack.f90, source/sixve.f90, source/track_thick.f90, source/track_thin.f90
There were a number of redundant arrays in the main particle array module, so I cleaned up a bit. Also added comments about what all the arrays are.
A bit difficult to see from the diff, but the deleted arrays are: `xsv`, `zsv`, `dp0v`, `sigmv6`, `dpsv6`, `xlv`, `zlv`, `nms`, and `ekkv`.
`dp0v` was always the same as `dpsv`, `nms` was always `one`, and `xlv` and `zlv` could be replaced by scalars. The rest weren't used at all.
In addition, `dpd`, `dpsq` and `ampv` can probably also be removed with a bit of tweaking of the code. They are all used as local temp arrays. So is `ejf0v`, but this one is used between particle loops.
=> Cleanup in mod_common_main

source/common_modules.f90, source/main_cr.f90, source/mod_boinc.f90, source/sixtrack_input.f90
This PR:
* Repositions the BOINC submodule to latest master where my fortran_api changes were merged.
* Fixes building for ifort/nagfor (didn't like `stop exitCode` so changed to `stop 1`).
* If postprocessing is on, tracking progress stops at 99%, and jumps to 100% after.
* Reshuffles a little bit how BOINC is finished due to the log file needing to be closed before ZIPF.
**Additional**
Do we really need two flags for BOINC and API? @kyrsjo asked the same question. This is why we need dummy routines, like `boincrf`, and it complicates the service module. I can't see any reason why we shouldn't just link BOINC with the API always. I suppose there was a reason for the test suite before perhaps, but the tests pass fine now.
=> Boinc API, bugfix and progress

test/beam-HO_6D-simple-newstyle-coupling/extra_checks.txt, test/beam-HO_6D-simple-newstyle-coupling/final_state.dat.canonical, test/tools/SixTestWrapper.cpp
The SixTestWrapper could still pass tests that actually didn't check anything at all, as it turns out it did for the test beam-HO_6D-simple-newstyle-coupling. This has now been fixed, and so has the test.
=> SixTestWrapper Fixes

source/checkpoint_restart.f90, source/mod_time.f90
Extracted the changes to `mod_time` from PR #878 as it is useful for the nightly builds which logs the time used from this module.
This updated module also shows the time spent writing checkpoint files, which can be useful. It's recorded in the file `sim_time.dat`.
=> Checkpointing Timing Module

source/collimation.f90, source/md5/md5interface.c
Fixes the following:
* A variable in collimation needs to be public so beamgas can see it.
* Minor issue with stripping `\r` for the md5 library on Windows: `fwrite` does not return an error value, but the number of characters written. This means the error if was triggering on every line and spamming output.
=> Fix build of beamgas

CMakeLists.txt, doc/user_manual/chProcessing.tex, source/common_modules.f90, source/main_cr.f90, source/main_da.f90, source/mod_find.f90, source/mod_geometry.f90, source/six_fox.f90, source/sixtrack.f90, source/sixtrack_input.f90
The input parsing was pretty dodgy here. No checks that the elements exist (although this is done later in the code) and no check that the main block flag `ichrom` was set to a valid value.
Flag `ichrom = 3` was not documented in the manual. It has been added.
Also added a few lattice search routines from a different PR, but due to circular dependencies added them to a new module `mod_find`. I am planning to add more here in the future.
In addition, I renamed the global variable `is` to `crois` as it already has name conflicts with some da variables. There was already a da-version of it called `issss`. The variables hold the indices of the single elements selected in the `CHRO` block.
=> Chromaticity block updates

source/beamgas.f90
Fixed beamgas build failing due to deleted collimation array
=> Fix BEAMGAS (again)

source/track_thin.f90
Apparently the total particle number in track progress printout sometimes overflows. I cannot reproduce the error, so just trying blindly to fix it.
=> Track Progress Printout Fix

doc/user_manual/chExtraOutput.tex
Just looked at the variables definitions in the DUMP section.
I added the scaling factor for xp & yp, but for consistency, I removed those and updated the units instead. Also, the array variable for momentum was wrong.
The delta array should also be scaled by 1000, right?
Also, if ejfv is "Pc", shouldn't e0f be "P0 c"?
=> Further Manual Updates

CMakeLists.txt, test/CMakeLists.txt, test/dist_file_6d/extra_inputs.txt
Some build options and tests failed on the nightly.
* DISTlib does not work with single or quad math. Since we're using intent(inout) in the interface, it's not as trivial as casting the values to double on the way in. Therefore DISTlib must be disabled when running single or quad.
* The tests for DISTlib cannot be run when STF flag is off as they have more than 64 particles.
* One test was missing extra_inputs.txt for BOINC.
=> Test suite fixes with new DIST block tests

source/dump.f90, source/fma.f90, source/include/umlalid.f90, source/main_cr.f90, source/six_fox.f90
This PR replaces the `dumptas`, `dumptasinv`, and `dumpclo` arrays in `DUMP` with an array of structs that is expanded only when there is an element with a dump assigned to it. An integer map points between the element index and the storage array index.
This saves quite a bit of memory. For n FCC test with 60 particles it saves 33%, and for a HL-LHC test with 2000 particles it save 24%.
=> Compact DUMP TAS

source/dump.f90
Forgot to check that the index is non-zero when reading the tas matrix in the actual dump routines. These now use the dum_getTasMatrix call which does the check automatically.
Also, when cleaning up the header, forgot to check that the subroutines had the use statements it needed also under the CR flag.
Additional note: The tas matrix should probably be saved in a global module instead of under DUMP. especially since it is already shared with FMA. Will probably move this when PR #929 is merged, because there all the linopt stuff is moved to a separate file.
=> Bugfixes for Compact TAS PR

source/checkpoint_restart.f90
Not sure how this happened ...
Must have accidentally hit the replace key when searching for line continuation characters in the source.
=> Bug: Line wrapping gone from checkpoint/restart

source/mod_dist.f90
Longitudinal emittance in DIST should be eVs not MeVs (scaling of reference energy was missing).
=> Bug in DIST longitudinal emittance conversion

source/mod_geometry.f90, source/sixtrack.f90
There was no check that the element position in the multicolumn version of the struct block was equal or larger than the previous element. This PR adds this check, and also improves the error reporting on fort.2 so that it is as detailed as that of fort.3.
=> Element position check for multicolumn SRUCT block

source/mod_utils.f90
Wrong operator in if-statement causing division by zero.
Or may have been infinity actually ...
=> Bugfix illegal floating point operation in wwerf

source/collimation.f90, test/CMakeLists.txt
Fixes the following:
* Build with HDF5
* Disables the new jaw fit tests when STF is off.
* Also turns off the K2 test with STF off as it uses 20000 particles.
=> Bugfixes for Collimation Jaw Fit PRs

source/main_cr.f90
The exit routine in collimation is called with a different condition than the init routine, causing the final summary files to not be written when running a thin 4D setup.
=> Minor Bugfix on Collimation Exit

source/track_thin.f90
Should only look up cdb_elemMap array if do_coll is true
Fails on boundary check with Debug build.
=> Minor bug in thin tracking for collimator check

source/splitSingletrack/mod_splitSingletrack.f90, source/splitSingletrack/splitSingletrack.f90
Added padding of 44 x zero to the header of the splitSingletrack tool. Now matches code in postpr.
=> SplitTrack header fix

source/collimation.f90
Was missing a single `use root_output` in exit collimator routine. SixTrack part seems to build now.
=> Add a missing use root_output

doc/user_manual/chIntroduction.tex, source/common_modules.f90, source/main_cr.f90, source/sixtrack_input.f90
This PR adds a command line `--notrack` flag that skips tracking.
This is for instance useful for checking the input for larger SixTrack jobs before they are run.
=> Notrack flag

doc/user_manual/chSpecialElements.tex, source/collimation.f90, test/collimation_cry_ge_am_hor_b2/fort.3, test/collimation_cry_ge_vc_ver_b1/fort.3, test/collimation_cry_si_ch_hor_b1/fort.3, test/collimation_cry_si_vr_ver_b2/fort.3
This PR changes to logic of the writing of crystal collimation files so that the interaction file is only written when the `WRITE_CRYCOORD` flag is enabled, and the entrance and exit files are only written if, in addition, the global `DEBUG` flag is set.
Tests and documentation updated accordingly.
=> Crystal files

CHANGELOG.md, source/dynk.f90, source/mod_units.f90, source/scatter.f90
This PR just moves the reposition files routine from the scatter module to mod_units, so it can be used by any module. This is especially useful for collimation.
The routine has been cleaned up a bit, made general (also should work outside of C/R) and more comments added.
=> Reposition files routine

source/collimation.f90
Apparently the test was failing because a variable was not properly initialised.
It has never been, actually, also when I set the test, but this was not caught by neither me preparing the test nor circleci catching it... But re-running the test with the master branch did fail...
=> fixing test of type 3 pencil beam

CHANGELOG.md, source/mainarrays.f90
In case secondary particles are injected in the tracking arrays, `pairID` and `pairMap` arrays are extended, with an initialisation to 0. This leads the `updatePairMap` subroutine to crash, as `pairMap(0,0)` would be updated for all secondary particles, out of bounds.
The fix is simple, i.e. to update the `pairMap` only for what concerns primary particles. The `pairMap` is anyway regularly expanded to keep the reshuffling algorithm smooth, without may exceptions.
Thanks to @JamesMolson for spotting the problem, in the context of the Fluka-SixTrack coupling.
=> Bug fix: update pairMap only in case of primary beam particles

doc/user_manual/chInitialConditions.tex, source/mod_dist.f90
Presently, if the `xp` or `yp` columns are present in a `FORMAT` statement, the unit stated by the user is ignored and the numbers are read in mrad. This is a problem in case of a file generated with `gpdist` (in the context of the Fluka-SixTrack coupling) in case of partially stripped ions or unstable hadrons, where the format of the file is non standard and a `FORMAT` statement is hence needed, but `xp` and `yp` are expressed in rad and not in mrad.
This PR aims at giving the possibility to parse the units of `xp` and `yp` in a `FORMAT` statement. Accepted values are `[1], [1000], [RAD], [MRAD]`.
User manual changed accordingly.
=> parsing unit of `xp` and `yp` in `FORMAT` keyword in `DIST` block

CHANGELOG.md, source/include/lostpart.f90, source/main_cr.f90
This is a continuation of PR #1050.
Here we remove any update of `napxo` that was still done in the context of the Fluka-SixTrack coupling, presently useless as the concerned loop can be run on `napx`.
Continuing on the comment https://github.com/SixTrack/SixTrack/pull/1050#issuecomment-580291211 by @vkbo :
> My point was to assign them anyway to prevent out of bounds errors and garbage values from memory in the analysis.
I agree with you on this, that's good, and it stays like that with these PRs.
> I added checks to catch this to avoid exactly this. Running PostPR on secondaries will therefore hit my bug trap, as intended.
I agree with you also on this, that's good, and it stays like that with these PRs. The loop in post-processing goes with `napxo`, hence having removed its (useless) …
=> Fix pair map (continued)

CHANGELOG.md, source/collimation.f90, source/g4collimation/CollimationMaterials.cpp, source/main_cr.f90, source/mod_particles.f90, source/track_thick.f90, source/track_thin.f90, source/tracking.f90
Missing #ifndefs as previously added for FLUKA (for pair map related topics).
Treat all particles as secondaries for the pair mapping with geant4 (i.e. just disable it).
Add Si as a material for geant4.
=> Update geant4 based collimation

source/elens.f90, source/scatter.f90, test/elensidealthin6d_FOX_uniform/extra_inputs.txt
This PR fixes three bugs:
* The C/R build for the elens module (Issue #1064)
* One of the elens tests had a non-existent file in extra_inputs.txt, which is used to generate the Sixin.zip file. This broke BOINC build.
* The check of parameters for the FIXED target profile type in the SCATTER block was set to the wrong value.
=> Fix CR build, elens test for BOINC, and SCATTER parsing bug

CMakeLists.txt, source/constants.f90, source/crlibm/crlibm_private.h
So I tried to build with gcc/gfortran 10, and it currently does not.
This pr should fix that.
I had to disable building with distlib since it fails to link. The problem there seems to be a lack of header guards so the same variables are now pulled in multiple times and you get the same symbols defined multiple times. That would need to be fixed by @tpersson since it is in a separate repo.
crlibm had a similar issue which came from some internal diagnostic code that we don't need, so I just disabled that. This also should speed things up a tiny bit.
=> Fix building with gcc >=10

CHANGELOG.md, source/collimation.f90, source/g4collimation/CollimationParticleGun.cpp, source/g4collimation/CollimationParticleGun.h, source/g4collimation/G4Interface.cpp
I finally enable the conversion of sigmv to time inside geant4.
dumping out the longitudinal phase space for a test bunch over 1000 turns makes the same pattern as for normal tracking.
=> Fix the time coordinate with geant4 collimation.

source/coll_k2.f90
In the previous PR I had the saving of the incoming nucleon count + energy at the start of the particle loop. Following this is a check for 1 sided collimators, that if a particle fails, it skips to the next particle. It would then never balance out the outgoing energy at the end of the particle loop leading to crazy energy losses in the fort.208 file.
This fixes it by just moving the logging to after the single side check.
=> Move the nucleon/energy logging in k2 collimation to after the single sided collimator check

source/collimation.f90, source/g4collimation/CollimationTrackingAction.cpp, source/g4collimation/CollimationTrackingAction.h, source/g4collimation/G4Interface.cpp, source/geant4.f90, source/mod_fluka.f90
Fairly simple...
We set mtc = 0 for neutrals.
This may have unintended outcomes if you don't know what you're doing, but you have to manually turn it on in both codes.
The fluka server code has already been updated to support this.
=> Add support for dealing with neutral particles in G4/FLUKA

source/elens.f90
Corrected bug which multiplied the kick of the HEL beam with gamma_electrons. Replaced gamma_e by 1.
=> fixed bug in electron lens kick: removed gamma_electrons
