SixTrack/sixtrack.s

This implements FIR (Finite Impulse Response) and IIR (Infinite Impulse Response) filter FUNs in DYNK. The implementation have been tested and works well with both normal and collimation version of SixTrack.

FIR and IIR in DYNK, version bump to 4.5.28

---

SixTrack/sixtrack.s

Remember to close unit 664 after reading the FIR/IIR file

---

SixTrack/sixtrack.s

Updated string matching logic to recognize new collimator names (TCTPV, TCTPH, TCSP)

collimation fix

---

SixTrack/sixtrack.s

- Detect if no particles will be tracked (such as if there is no collimation block)
- Detect if initial distribution file is missing
- Use an unused FORTRAN unit number when loading initial distribution
- Detect if collimation database is missing and output appropriate error message

Improved error detection and bugfixes in COLLIMAT:

---

SixTrack/sixtrack.s

Single diffraction differential cross section typo fix

---

SixTrack/sixtrack.s

Such as if it is supposed to be applied from turn 10 onwards, and has a turnshift of 10...

Detect if DYNK's FILE function is called with a turn less than 1

---

SixTrack/sixtrack.s

Thanks to Miriam for pointing that out!
This pull request replaces #53, where I did something stupid and caused a very unnecessary merge conflict.

Add missing prror() calls after detecting a bug.

---

SixTrack/sixtrack.s

Merge this as soon as the BDEX mess has been cleaned up.
Fixes #61

Properly initialize all of DYNK in COMNUL.

---

SixTrack/make_six

Delete some double-checks in make_six -> making the code more readable.

cleanup in make_six

---

SixTrack/pytools/SixRipken.py
SixTrack/pytools/read_fortbin.py

created new folder pytools with read_fortbin.py and SixRipken.py

add python tools to SixTrack

---

SixTest/bin/Makefile
SixTest/fma/extra_checks.txt

SixTest fixes

---

SixTrack/sixtrack.s

In order to fix issue #120 . The new output format works with beamLossPattern without any change - I tested it.

Change output format for tracks2.dat

---

SixTrack/dafor.f
SixTrack/make_six

Improvements to DAFOR:
* Allow command line arguments for input- and output files
* Fix all compilation warnings
* Trap some use of undefined variables.
* Stop with a non-zero return value in case of error
* Close all files when done.

Dafor improvements

---

SixTrack/sixtrack.s

Collimat stop

---

SixTrack/sixtrack.s

Small DYNK fixes

---

SixTrack/plato_seq.s
SixTrack/sixtrack.s

Hi Miriam @mfittere,
could you look at these modifications to FMA, especially the 4D tracking stuff?
Andri @androula crashed the program hard by running FMA on Thick4D results; I think I fixed it by basically just skipping the 3rd mode...

FMA fixes: DUMP max turn = -1, 4D tracking

---

CMakeLists.txt
SixTest/CMakeLists.txt

This just adds some labels to the tests, so you can run ctest -L blabla and only get a subset of the tests. Each test can have multiple labels.
So far I have:
fast: for tests < ~60 seconds run time
medium: say < ~30 minutes run time
slow: everything else, i.e. prob1 and prob3 currently.

cmake updates.

---

CMakeLists.txt

Fix static building on MSYS2.

---

.gitignore
Doc/building_sixtrack/building_sixtrack.tex

Working on the build manual. @JamesMolson , you're welcome to contribute -- especially if you could fill out the CDASH section? I'll be writing something more in Chapter 1.1 soon (I have the text 95% done in another document).

Build manual

---

SixTrack/roundctl/dtoa_c.c
SixTrack/roundctl/dtoaf.c
SixTrack/roundctl/round_near.c

Rename strtod function.

---

CMakeLists.txt
Doc/building_sixtrack/building_sixtrack.tex

Cmake on OSX updates

---

CMakeLists.txt
SixTest/CMakeLists.txt
SixTest/bin/SixTestWrapper.cpp

This is a slightly less insane way of doing things for CR tests.
Needs to be merged then re-tested with the BOINC ZIPIT patch.

Update the testing suite to work in a more sane way with CR and BOINC.

---

SixTrack/sixtrack.s

Celebrating that all tests pass, Windows works, and things are in general pretty good.

Bump version to 4.6.3

---

SixTrack/sixtrack.s

I think you can just merge as the change is so small.

allow case that wire separation is zero in one plane

---

CMakeLists.txt

I forgot to update a target in CMakeLists.txt

Fix building old astuce with nagfor

---

Doc/building_sixtrack/makefile
Doc/physics_manual/makefile
Doc/user_manual/makefile

In particular, improving the one in physics_manual and creating a couple of new ones for building_sixtrack and user_manual
...very very dirty ones: nothing subtle, simply something for cleaning tex files and automatically compile...

Improving Doc makefiles

---

Doc/user_manual/six.tex
SixTrack/sixtrack.s

Increase nbb to 500 for big and hugenblz

---

SixTrack/sixtrack.s

Fix beambeam nosync

---

SixTrack/sixtrack.s

Partial fix/protection for #224; full fix will have to wait until after the refactoring has been merged.

Collimation max turns

---

Doc/building_sixtrack/building_sixtrack.tex

update build manual

---

SixTrack/buildLibraries.sh
SixTrack/libArchiveTester.cpp

Libarchive didn't look for the zlib header in the local zlib folder, taking instead the system ones. This caused it not to link to zlib.
Found while building on GNU Hurd :)

Improve zlib build

---

Doc/user_manual/six.tex
SixTrack/scatter.s90

* Adds offset to Gaussian beam profile.
* Some minor changes to floating point values in calculations.
* Cleaned up some indenting inconsistencies left over from fixed form code.

Scatter Update 2

---

SixTrack/sixtrack.s

Fix counting of lines for DUMP formats 7 and 8 and avoid excessive flushing. This fixes #364 .

Fix CR for DUMP 7 and 8

---

SixTrack/dump.s90

Now looks like actual Fortran Free Form (TM)
@kyrsjo

File dump.s90 reflow and prettified

---

SixTrack/common_modules.s90
SixTrack/sixtrack.s

Fluka coupling fixes

---

CMakeLists.txt
SixTrack/ast_mask/crcoall.ast
SixTrack/ast_mask/file_units.ast
SixTrack/common_modules.s90
SixTrack/dynk.s90
SixTrack/file_units.s90
SixTrack/scatter.s90
SixTrack/sixtrack.s90

Added a module file_units that will assign an available file unit to a given output file. By default, it assigns from unit number 1000 to 1999. This range appears to be mostly unused, but the class will test that it actually is unused at the time it is requested.
* Should track what files get assigned what unit, if only so the information can be dumped for debugging purposes. [Done]
* Add to DYNK. [Done]
* Add to DUMP module for file units set to -1 in fort.3.

Fileunit module

---

CMakeLists.txt

Added a loop to set pp definitions only for target SixTrack.

Cleaned up generation of preprocessor flags in CMakeLists

---

CMakeLists.txt
SixTrack/ast_mask/bouncy_castle.ast
SixTrack/ast_mask/plato_seq.ast
SixTrack/ast_mask/ranecu.ast
SixTrack/ast_mask/root_output.ast
SixTrack/ast_mask/wire.ast
SixTrack/bouncy_castle.f90
SixTrack/plato_seq.f90
SixTrack/ranecu.f90
SixTrack/root_output.f90
SixTrack/wire.f90

Renaming files with no +ca block to f90.

s90 to f90 renaming

---

SixTrack/collimation.s90
SixTrack/scatter.s90
SixTrack/sixtrack.s90
SixTrack/sixtrack_input.f90
SixTrack/string_tools.f90

Added more error output when casting numbers to real or int.
Also added an input DEBUG flag for fort.3.
When the DEBUG flag is added to after GEOM/FREE, parsed input values will be echoed back.

Bug fix and additional error info

---

SixTrack/hdf5_output.f90
SixTrack/scatter.s90

Added HDF5 attribute routines to the HDF5 module.

HDF5 Attributes

---

SixTrack/common_modules.f90
SixTrack/end_sixtrack.f90
SixTrack/sixtrack.f90
SixTrack/sixtrack_input.f90

Moves MULT parsing to sixtrack_input
Cleans up unused variables in daten.

Cleanup MULT and unused variables

---

source/main_cr.f90
source/main_da.f90
source/mod_fluc.f90
source/mod_units.f90
source/sixda.f90

The writing of fort.4 does not fully match fort.2, so updated the routine.
Also moved the opening and closing of fort.4 to where it is written.

Updated writing of fort.4 to match the format of fort.2

---

doc/user_manual/apxDataStructure.tex
doc/user_manual/apxExamples.tex
doc/user_manual/apxInputOutput.tex
doc/user_manual/apxKeywords.tex
doc/user_manual/chExtraOutput.tex
doc/user_manual/chIntroduction.tex
doc/user_manual/chMachineGeometry.tex
doc/user_manual/chProcessing.tex
doc/user_manual/chSpecialElements.tex
doc/user_manual/six.tex
doc/user_manual/theBibliography.tex
source/beam6d.f90
source/beam6d_fox.f90
source/checkpoint_restart.f90
source/collimation.f90
source/dump.f90
source/hions.f90
source/mainarrays.f90
source/sixve.f90
source/track_thin.f90

Removed whitespaces at the end of line with
```
sed -i 's/\s\+$//g' *.f90 *.tex
```

remove whitespaces at the end of line

---

source/aperture.f90
source/end_sixtrack.f90
source/file_units.f90
source/main_cr.f90
source/main_da.f90
source/sixtrack.f90
test/fileunits_DYNK_DUMP/file_units.dat.canonical

Some cleanup in daten
Rewritten parts of module file_units
Fixed a bug in reading aperture LIMIs from external file.

Bug fixes and some cleanup

---

source/aperture.f90
source/bdex.f90
source/beamgas.f90
source/checkpoint_restart.f90
source/collimation.f90
source/end_sixtrack.f90
source/hions.f90
source/main_cr.f90
source/matrix_inv.f90
source/ranlux.f90
source/sixve.f90
source/track_thin.f90

Rewrites the end of MAINCR particle summary output and makes it all go away if QUIET >= 2 unless particles are lost.
Cleaned up the computing time summary a bit.
Cleaned up a bunch of write(lout,*) many places in the code.

Cleaned up particle summary and made it obey the quiet flag.

---

CMakeLists.txt

Minor cleanup and fixes commits to be merged in a bit.

Minor cleanup and fixes

---

source/include/mul4v05.f90

Added a couple more missing brackets.

---

.gitattributes

Fixed some errors in .gitattributes from #610

Fixed some errors in .gitattributes.

---

.gitignore
doc/generateForWeb.sh

Updated the manual build scripts so they can be run by a crontab job to build the manual automatically.

Updated manual build scripts.

---

test/CMakeLists.txt
test/scatter_collimation/dump_ip1.dat.canonical
test/scatter_collimation/dump_ip5.dat.canonical

Fix header of scatter_collimation and mark it as a fast test

---

CMakeLists.txt

Add first 7 values of git hash to executable name.
I.e. SixTrack_50002-851e081_...

Add first 7 values of git hash to executable name.

---

source/track_thick.f90
source/track_thin.f90

Also removed comments that were confusing.

Fixed index in track_thick trombone. Same fix was already done for track_thin.

---

source/common_modules.f90
source/debug_dump.f90
source/end_sixtrack.f90
source/include/alignva.f90
source/include/alignvb.f90
source/include/stra01.f90
source/include/stra02.f90
source/include/stra03.f90
source/include/stra04.f90
source/include/stra05.f90
source/include/stra06.f90
source/include/stra07.f90
source/include/stra08.f90
source/include/stra09.f90
source/include/stra10.f90
source/main_cr.f90
source/mod_fluc.f90
source/postprocessing.f90
source/sixtrack.f90
source/sixve.f90
source/track_thick.f90
source/track_thin.f90

Remove Multiple Machines (m, mmac, nmac)

Remove Multiple Machines (m, mmac, nmac)

---

CMakeLists.txt

Increase required cmake version to >= 3.2

Increase required cmake version to >= 3.2

---

source/end_sixtrack.f90
source/include/beams1.f90
source/main_cr.f90
source/main_da.f90
source/six_fox.f90
source/sixda.f90
source/sixtrack.f90
source/sixtrack_input.f90
source/sixve.f90

Most of the error messages have already been put in place where the error occurs. This PR moves the remaining error messages as well, and cleans up the prror subroutine.

Error Messages

---

source/elens.f90

Fixed minor bug that causes confusing error message in elens for missing element.

Minor elens input parsing bug

---

.circleci/config.yml

Bump the repository limit check by 10 MB

---

source/checkpoint_restart.f90
source/elens.f90
source/include/kickelens.f90

More in detail, this PR includes:
* parenthetisation;
* CR `betrel`;
* management of file units via `units_openUnit` (i.e. radial profiles and chebyshev coefficients (not active yet...));

make elens module BOINC-compatible

---

doc/user_manual/chSpecialElements.tex
source/checkpoint_restart.f90
source/dynk.f90
source/elens.f90
source/scatter.f90
source/sixtrack.f90

Fixing some small corner cases in the new ELENS implementation when used with DYNK energy ramp.

Elens dynk cornercase

---

CHANGELOG.md
doc/user_manual/apxInputOutput.tex
doc/user_manual/chExtraOutput.tex
doc/user_manual/chIntroduction.tex
doc/user_manual/chSpecialElements.tex
doc/user_manual/incTitlePage.tex
source/version.f90

Release 5.1 Changelog and Version Bump
Assuming release on Monday is a go.

Release 5.1 Changelog and Version Bump

---

source/mod_fluc.f90

A missing open for fort.2 that made nagfor unhappy.

Nagfor fixes

---

doc/user_manual/chSpecialElements.tex

This fixes the issue #773 
....and it compiles ! :)

Fixes the table for DYNK

---

CMakeLists.txt
source/dabnew.f90
source/debug_dump.f90
source/main_cr.f90
source/mainarrays.f90
source/mod_alloc.f90
source/scatter.f90
source/track_thick.f90

Fixes `DEBUG` build (compiler flag)
Fixes an uninitialised error flag in `scatter_crpoint`

Fixes for 5.2

---

source/sixtrack.f90

Removed two no longer needed routines in sixtrack.f90 and closed a few subroutines properly.

Minor cleanup in sixtrack.f90

---

source/track_thick.f90
source/track_thin.f90

It just combines the turn counting info that is already there with the particle count. The latter is convenient when there are losses.
I put it into a routine that computes the formatting string the first time it's called.

Added a more detailed turn counting report in tracking

---

CHANGELOG.md
doc/user_manual/incTitlePage.tex
source/version.f90

Bumped version to 5.2.10 and updated changelog

Release 5.2.10

---

source/mod_fluka.f90

As found out with Alessio, a little bug that made fort.208 completely useless...

Fixed the elemement indexes for the fort.208 and fort.209

---

CHANGELOG.md
doc/user_manual/incTitlePage.tex
source/version.f90

Release 5.3.2

---

source/pdgid.f90

This file is not properly indented and has unnecessary use keyword in module header (bleed-through).

Indentation

---

doc/user_manual/chSpecialElements.tex
doc/user_manual/theBibliography.tex
source/coll_crystal.f90

The "Special elements" section of the user manual has been updated with information on crystal collimators, including the description of the additional parameters required by the collimator database as well as appropriate references.

Documentation update for crystal collimators

---

source/root_output.f90
source/root_output/RunTime_root.cpp
source/root_output/RunTime_root.h

This had stopped working and I could not work out why.
Anyway change floats -> doubles and it builds.

Fix root output compiling

---

source/scatter.f90
source/tracking.f90

A couple of bugfixes for Intel QUAD build and repositioning of the scatter_summary.dat file when C/R.

Scatter Bugfixes

---

source/main_cr.f90

Fix the root build (excess variables were deleted earlier).

---

CHANGELOG.md
source/g4collimation/CollimationParticleGun.cpp
source/main_cr.f90
source/mod_fluka.f90

Print the error codes with fluka.
Add a mass tolerance in geant4.

Small update for FLUKA coupling output + geant4

---

CHANGELOG.md
source/collimation.f90
source/g4collimation/CMakeLists.txt
source/g4collimation/CollimationEventAction.cpp
source/g4collimation/CollimationGeometry.cpp
source/g4collimation/CollimationGeometry.h
source/g4collimation/G4Interface.cpp
source/geant4.f90

1: Fix building with the latest g4 release
2: Fix a warning about a missing quote.

Minor geant4 updates

---

CHANGELOG.md
doc/building_sixtrack/building_sixtrack.tex
doc/user_manual/chInitialConditions.tex
doc/user_manual/chSpecialElements.tex
source/aperture.f90
source/checkpoint_restart.f90
source/collimation.f90
source/common_modules.f90
source/dump.f90
source/g4collimation/CMakeLists.txt
source/g4collimation/CollimationEMD.cpp
source/g4collimation/CollimationEMD.h
source/g4collimation/CollimationMaterials.cpp
source/g4collimation/CollimationParticleGun.cpp
source/g4collimation/CollimationParticleGun.h
source/g4collimation/CollimationStorage.h
source/g4collimation/CollimationTrackingAction.cpp
source/g4collimation/CollimationTrackingAction.h
source/g4collimation/G4Interface.cpp
source/geant4.f90
source/main_cr.f90
source/mod_fluka.f90
source/root_output.f90
source/sixtrack_input.f90

still in progress for geant4
@amereghe could you look at what has been done so far for the FLUKA coupling, and see if you can spot anything stupid I've done (or have missed)?

Update particle/parent IDs + weight + other FLUKA/geant4 changes

---

source/mod_fluka.f90

Fixed call to file position variable in mod_fluka

Fixed call to file position variable in mod_fluka
